[functions]
  node_bundler = "esbuild"
  included_files = ["src/markdown/*.md"]

[build]
  command = "npm run build"
  functions = "functions"


[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/.netlify/functions/server/static/*"
  status = 200